import * as fs from 'node:fs';
import * as path from 'node:path';
import * as ts from 'typescript';

import {type DiagnosticCollector} from '../DiagnosticCollector';
import {stripSoraTagsFromComment} from './JSDocUtils';
import {type TransformedDeclaration} from './Transformer';
import {type ResolvedType} from './TypeResolver';

const fileHeader = '// Auto-generated by sora export:api\n\n';

interface PrintEntry {
  node: ts.Node;
  sourceFile: ts.SourceFile;
  name: string;
}

function stripSoraTagsFromOutput(output: string): string {
  return output.replace(/\/\*\*[\s\S]*?\*\//g, (match) => {
    const stripped = stripSoraTagsFromComment(match);
    if (!stripped) return '';

    const inner = stripped
      .replace(/^\/\*\*?/, '')
      .replace(/\*\/$/, '')
      .replace(/\*/g, '')
      .trim();
    if (!inner) return '';

    return stripped;
  }).replace(/\n{3,}/g, '\n\n');
}

class Emitter {
  private outputBasePath_: string;
  private diagnostics_: DiagnosticCollector | null;

  constructor(outputBasePath: string, diagnostics?: DiagnosticCollector) {
    this.outputBasePath_ = outputBasePath;
    this.diagnostics_ = diagnostics || null;
  }

  emitFile(
    declarations: TransformedDeclaration[],
    enumDeclarations: TransformedDeclaration[],
    typeDependencies: ResolvedType[],
    suffix?: string
  ): void {
    const printer = ts.createPrinter({
      newLine: ts.NewLineKind.LineFeed,
    });

    const seen = new Set<string>();
    const entries: PrintEntry[] = [];

    const addEntry = (name: string, node: ts.Node, sourceFile: ts.SourceFile) => {
      if (seen.has(name)) {
        if (this.diagnostics_) {
          this.diagnostics_.addWarning(
            `Duplicate type name '${name}' found. Only the first occurrence will be exported.`
          );
        }
        return;
      }
      seen.add(name);
      entries.push({node, sourceFile, name});
    };

    for (const d of declarations) {
      addEntry(d.name, d.node, d.sourceFile);
    }
    for (const d of enumDeclarations) {
      addEntry(d.name, d.node, d.sourceFile);
    }
    for (const t of typeDependencies) {
      addEntry(t.name, t.node, t.sourceFile);
    }

    if (entries.length === 0 && this.diagnostics_) {
      this.diagnostics_.addWarning(
        'No declarations to emit. Output file will be empty.'
      );
    }

    const raw = entries.map(({node, sourceFile}) => {
      return printer.printNode(ts.EmitHint.Unspecified, node, sourceFile);
    }).join('\n\n');

    const stripped = stripSoraTagsFromOutput(raw);
    const content = fileHeader + stripped.replace(/^( {4})+/gm, match => '  '.repeat(match.length / 4));

    const outputPath = suffix
      ? `${this.outputBasePath_}.${suffix}.ts`
      : `${this.outputBasePath_}.ts`;

    this.ensureDirectory(outputPath);

    try {
      fs.writeFileSync(outputPath, content);
    } catch (err: any) {
      throw new Error(`Failed to write output file '${outputPath}': ${err.message}`);
    }
  }

  private ensureDirectory(filePath: string) {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, {recursive: true});
    }
  }
}

export {Emitter};
